---
title: "SIBECOL Dataton"
output: 
  flexdashboard::flex_dashboard:
    social: menu [ "twitter", "facebook"]
---

```{r setup, include=FALSE}
library(flexdashboard)
library(knitr)
# logo: logo.png #48 pixels
# favicon: favicon.png
```

Output {data-orientation=rows}
=========================================

Row {data-height=800, data-padding=50}
-------------------------------------

### Iberian biodiversity ...

```{r map occurrence, echo=FALSE, message=FALSE, warning=FALSE}
library("leaflet")
library("htmltools")
dat <- read.csv(file = "_data/data.csv")
dat$content <- paste("<b>", dat$species, "</a></b>", "<br/>", 
  dat$family, "<br/>", sep = "")
pal <- colorFactor(
  palette = "Spectral",
  domain = dat$family
) #maybe check family NA?
map <- leaflet(dat)
map1.5 <- addTiles(map)
map2 <- addCircleMarkers(map = map1.5, lng = dat$decimalLongitude, 
                   lat = dat$decimalLatitude, 
                   label = ~htmlEscape(species),
                   popup = ~content,
                   color = ~pal(family),
                   clusterOptions = markerClusterOptions())
addLegend(map = map2, position = "bottomright", 
          pal = pal, values = ~unique(dat$family),
    title = "taxa",
    opacity = 1)
```



Row {data-height=200}
-------------------------------------

### What's this?

This is the output of the first EcoInf dataton!

